-- ############################################################################
-- WARNING: THIS SCRIPT WILL ERASE THE 'dev' SCHEMA CREATED FOR THE
-- PAYLOCITY CODING CHALLENGE, WHICH INCLUDES THE TABLES. IT WILL ALSO
-- ERASE THE ROLES AND USERS CREATED BY THE SET-UP SCRIPT.
--
-- IF THE DATBASE THROWS AN ERROR WHILE TRYING TO RUN THIS SCRIPT, THEN
-- UNEXPECTED CHANGES HAVE BEEN MADE TO THE 'dev' SCHEMA. TO RESOLVE SUCH
-- CONFLICTS, PLEASE CONSULT A POSTGRESQL DBA TO HELP YOU.
-- ############################################################################
  
  REVOKE ALL PRIVILEGES
  ON SCHEMA dev
  FROM emilgram;

  DROP USER emilgram;

  REVOKE ALL PRIVILEGES
  ON SCHEMA dev
  FROM pccdev;

  REVOKE ALL PRIVILEGES
  ON DATABASE paylocity
  FROM pccdev;

  DROP SCHEMA dev CASCADE;

  DROP ROLE pccdev;