---
title: "Paylocity Coding Challenge: README"
author: "Eric Milgram, PhD"
date: "December 23, 2021"
knit: (function(inputFile, encoding) {
        rmarkdown::render(
              input = inputFile,
              encoding = encoding,
              output_dir = here::here("."))
        }
      )
output:
  md_document:
    toc: no
    number_sections: no
    variant: gfm
---

```{r setup, include=FALSE}
library(here)
library(gluedown)

knitr::opts_chunk$set(echo = FALSE, include = TRUE, results = "hold", message = FALSE)
```

```{css, echo = FALSE}

pre {
  max-height: 800px !important;
  overflow-y: auto !important;
  overflow-x: scroll !important;
}

pre code {
  white-space: pre
}

#titleBox {
  border: solid medium black;
  padding: 1em;
  margin: 2em;
}

.titleBoxItemDescriptor, .titleBoxItemValue {
  border: solid thin black;
}

.titleBoxItemDescriptor {
  text-align: right;
  font-weight: bold;
}

.titleBoxItemValue {
  text-align: left;
}

.proofingOnly {
  width: 100%;
  border: solid thick red;
  border-radius: 25pt;
}

.sourceCodeText {
  font-family: courier, monospace, serif;
}

```

# Paylocity Coding Challenge: README

<div style="font-size: 1.5em; padding-bottom: 0;">Eric Milgram, PhD</div>
<table>
<tbody>
<tr>
  <td style="padding: 0; display: none;">
    <a href="https://github.com/ScientificProgrammer/PaylocityCodingChallenge">ScientificProgrammer/PaylocityCodingChallenge</a>
  </td>
</tr>
<tr>
  <td style="padding: 0;">
    Created: December 15, 2021
  </td>
</tr>
<tr>
  <td style="padding: 0;">
    Last Updated: `r Sys.time()`</span>
  </td>
</tr>
</tbody>
</table>


# Overview

## What is the purpose of this Github repo?

I created this Github repo was as part of candidate evaluation and
interview process for Paylocity. As part of this process, Paylocity
assesses a candidate's skill with programming in Python for developing database
applications and writing SQL, specifically for the PostgreSQL database server.
Paylocity refers to these exercises as the *Paylocity Coding Challenge*.

## What does this Github repo contain?
<div class="proofingOnlyContainer">
<div style="color: red; font-size: 1.5em; font-weight: bold;">
EXPLAIN THE CONTENTS OF THIS REPO, WITH SPECIFIC EMPHASIS ON THE
FOLLOWING ITEMS.
</div>
<ol>
<li>
  <div>MY INTERPRETATION OF THE PAYLOCITY CODING CHALLENGE</div>
  <ul>
    <li><a href="code/Markdown/pcc_010_challenge_overview.md">The broad overview</a></li>
    <li>Detailed instructions for <a href="code/Markdown/pcc_020-010_problem1_write_python_program.md">Problem 1: Writing a Python program.</a></li>
    <li>Detailed instructions for <a href="code/Markdown/pcc_020-020_problem2_sql_live_walkthrough.md">Problem 2: Live SQL Walk-through Exercise.</a></li>
  </ul>
</li>
<li>
  <p>THE STRUCTURE OF THE REPO: 3 key top level sub-directories</p>
<ol>
  <li><span class='sourceCodeText'><a href="./code">code</a></span> - All of my source code</li>
  <li><span class='sourceCodeText'><a href="./data">data</a></span> - All data used for the *Paylocity Coding Challenge*</li>
  <li><span class='sourceCodeText'><a href="./output">output</a></span> - Any output generated by my code</li>
</ol>
</li>
<li>
   <p>THE STRUCTURE OF THE <span class='sourceCodeText'>code</span> SUB-DIRECTORY</p>
   <ol>
    <li><span class='sourceCodeText'><a href="./code/Markdown">Markdown</a></span></li>
    <li><span class='sourceCodeText'><a href="./code/Python">Python</a></span></li>
    <li><span class='sourceCodeText'><a href="./code/R">R</a></span></li>
    <li><span class='sourceCodeText'><a href="./code/RMarkdown">RMarkdown</a></span></li>
    <li><span class='sourceCodeText'><a href="./code/SQL">SQL</a></span></li>
  </ol>
</li>
<li>
  <p>EXERCISE 1 OF 2: PROGRAMMING IN PYTHON</p>
  <ol>
    <li><p>CONCISE EXPLANATION OF THE PROBLEM WITH A LINK TO MY INTERPRETATION OF THE <a href='`r here::here("code/Markdown/pcc_010_challenge_overview.md")`'>PAYLOCITY CODING CHALLENGE</a></p></li>
    <li><p>CONCISE EXPLANATION OF MY CODING STRATEGY</p></li>
    <li>
      <p>HIGH LEVEL SUMMARY OF MY INFRASTRUCTURE: See my <a href="code/Markdown/pcc_100_system_description.md">Infrastructure Summary Page</a></p>
      <ul>
        <li>
          <div>VERSIONS OF PYTHON USED:</div>
          <ul>
            <li>MS Windows: <span style="font-family: courier new, courier, monospace, serif;">3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]</span></li>
            <li>Debian Linux - WSL <span style="font-family: courier new, courier, monospace, serif;">3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]</span></li>
          </ul>
        </li>
        <li>pgAdmin tool for DBA work</li>
        <li>AWS Infrastructure: 1) PG running on RDS (see <a href="./data/100_PCC_PostgreSQL_AWS_RDS_description.json">100_PCC_PostgreSQL_AWS_RDS_description.json</a>), 2) VPC Configuration, 3) CloudWatch Monitoring</li>
      </ul
    </li>
    <li>
      <p>HIGHLIGHT PORTIONS OF MY PYTHON CODE IN THE EXPLANATION OF MY CODING SOLUTION</p>
      <ul>
        <li><p>DESCRIPTION OF THE INPUT DATA FILE</p></li>
        <li><p>DESCRIBE THE 'CHALLENGE' WITH THE INPUT DATA FILE AS IT WAS FURNISHED AND THE DATA MODEL</p></li>
        <li><p>USE MY ERD TO ILLUSTRATE THE PROBLEM</p></li>
      <ul>
    </li>
  </ol>
</li>
<li>
  <p>EXERCISE 2 OF 2: SQL EXERCISES</p>
  <ol>
    <li><a href='https://example.com'>LINK-NOT-IMPLEMENTED-YET</a></li>
  </ol>
</li>
</ol>
</div>

---
